
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComp from "./components/header/HeaderComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {

  return (
    <html lang="en" id="HTML_item" className="light_mode">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
    <HeaderComp />
       <main>
        {children}
        </main>
      </body>
    </html>
  );
}
